/* The following code was generated by JFlex 1.6.1 */

/* JFlex example: partial Java language lexer specification */

package com.kerberus.model.syntaxValidator.rules.sql;


import java_cup.runtime.*; 		// Required to send lexemas to Cup
import java.util.LinkedList; 	// Required for LinkedList
import com.kerberus.model.syntaxValidator.rules.util.*;
import com.kerberus.model.syntaxValidator.rules.sql.sym;

/**
 * This class is a simple example lexer.
 */


public class JFlex_Rules_SQL implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\2\1\15\1\16\1\1\22\0\1\6\1\56\1\17"+
    "\2\0\1\60\1\61\1\13\1\64\1\65\1\4\1\57\1\67\1\5"+
    "\1\12\1\3\2\10\1\47\7\10\1\0\1\66\1\55\1\53\1\54"+
    "\2\0\1\31\1\44\1\24\1\30\1\22\1\40\1\46\1\43\1\33"+
    "\1\51\1\7\1\23\1\41\1\34\1\36\1\27\1\7\1\35\1\21"+
    "\1\25\1\26\1\37\1\42\1\52\1\45\1\50\1\0\1\14\1\0"+
    "\1\62\1\11\1\0\1\31\1\44\1\24\1\30\1\22\1\40\1\46"+
    "\1\43\1\33\1\51\1\7\1\23\1\41\1\34\1\36\1\27\1\7"+
    "\1\35\1\21\1\25\1\26\1\37\1\42\1\52\1\45\1\50\1\0"+
    "\1\63\10\0\1\15\252\0\2\32\115\0\1\20\u1ea8\0\1\15\1\15"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\4\1\10\6\1\1\14\6\1\10\1\11\1\12\1\1"+
    "\1\13\3\1\1\2\1\14\1\15\1\16\1\17\1\0"+
    "\1\20\1\21\1\22\1\23\3\0\1\24\5\0\1\25"+
    "\4\0\22\6\1\0\5\6\1\0\2\6\2\26\3\6"+
    "\1\27\1\0\1\30\1\27\1\6\1\30\10\6\1\0"+
    "\2\6\1\31\1\32\5\6\1\0\1\6\1\0\3\6"+
    "\1\33\2\6\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\2\0\2\22\1\45\1\0\1\46"+
    "\1\47\1\0\1\50\1\51\2\0\1\6\1\50\1\51"+
    "\2\6\1\0\1\6\1\52\5\6\1\0\6\6\1\0"+
    "\2\6\1\53\1\6\1\0\3\6\1\0\1\6\1\0"+
    "\3\6\1\0\2\6\2\54\1\55\1\56\1\57\1\0"+
    "\1\60\1\0\1\61\1\0\1\6\1\60\1\6\1\61"+
    "\5\6\1\62\1\63\4\6\1\0\11\6\1\64\2\65"+
    "\1\0\4\6\1\0\1\6\1\0\1\22\3\0\3\6"+
    "\2\66\1\6\1\67\1\0\1\6\1\70\1\6\2\71"+
    "\5\6\2\72\3\6\1\73\1\0\3\6\1\0\1\6"+
    "\2\74\1\6\1\75\1\0\1\6\1\76\3\0\1\77"+
    "\1\0\3\6\1\77\2\6\1\100\2\6\1\101\2\6"+
    "\1\0\1\6\1\102\1\0\5\6\1\103\1\104\2\6"+
    "\2\105\1\106\1\6\1\0\2\6\2\107\3\0\4\6"+
    "\2\110\1\111\1\6\1\112\1\6\1\0\1\6\1\113"+
    "\1\6\1\0\2\6\2\114\1\115\1\6\2\116\2\6"+
    "\1\0\1\6\2\0\1\117\1\120\2\6\1\117\1\120"+
    "\1\121\1\0\5\6\2\122\2\123\1\124\1\125\2\6"+
    "\1\126\1\6\1\127\1\0\1\6\1\130\1\131\2\0"+
    "\1\131\2\6\1\132\1\133\1\134\2\135\1\6\1\0"+
    "\2\6\1\136\1\137\1\0\1\6\1\0\1\6\1\140"+
    "\1\141\1\140\1\141\1\6\2\142\1\143\3\6\2\144"+
    "\2\6\2\145\1\0\1\146\1\6\1\146\1\147\1\0"+
    "\1\6\1\150\1\0\1\6\1\0\1\6\1\0\1\6"+
    "\1\151\1\6\1\152\1\153\1\154\2\155\1\0\1\6"+
    "\2\156\2\157\1\0\1\6\1\160\1\0\1\6\1\161"+
    "\1\0\1\6\1\0\2\6\1\0\2\6\1\0\1\6"+
    "\2\162\1\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\1\6\2\163\1\0\1\6\2\164\1\0"+
    "\1\6\1\0\1\6\2\165\2\166";

  private static int [] zzUnpackAction() {
    int [] result = new int[482];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\70\0\160\0\250\0\340\0\u0118\0\u0150"+
    "\0\u0188\0\u01c0\0\u01f8\0\u0230\0\u0268\0\u02a0\0\u02d8\0\u0310"+
    "\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498\0\u04d0"+
    "\0\u0508\0\u0540\0\u0578\0\u05b0\0\u05e8\0\u0620\0\u0658\0\u0690"+
    "\0\u06c8\0\70\0\u0700\0\u0738\0\u0770\0\u07a8\0\u07e0\0\u0818"+
    "\0\u0850\0\u0888\0\70\0\70\0\70\0\70\0\u08c0\0\70"+
    "\0\70\0\u08f8\0\70\0\u0930\0\u0968\0\u01c0\0\70\0\u09a0"+
    "\0\u09d8\0\u0a10\0\u0a48\0\u0a80\0\70\0\u0ab8\0\u0af0\0\u0b28"+
    "\0\u0b60\0\u0b98\0\u0bd0\0\u0c08\0\u0c40\0\u0c78\0\u0cb0\0\u0ce8"+
    "\0\u0d20\0\u0d58\0\u0d90\0\u0dc8\0\u0e00\0\u0e38\0\u0e70\0\u0ea8"+
    "\0\u0ee0\0\u0f18\0\u0f50\0\u0f88\0\u0fc0\0\u0ff8\0\u1030\0\u1068"+
    "\0\u10a0\0\u10d8\0\u1110\0\u1148\0\u1180\0\u11b8\0\u11f0\0\u1228"+
    "\0\u1260\0\u1298\0\u12d0\0\u1308\0\u1340\0\u1378\0\u13b0\0\u13e8"+
    "\0\u1420\0\u1458\0\u1490\0\u14c8\0\u1500\0\u1538\0\u1570\0\u15a8"+
    "\0\u15e0\0\u1618\0\u0118\0\u1650\0\u1688\0\u16c0\0\u16f8\0\u1730"+
    "\0\u1768\0\u17a0\0\u17d8\0\u1810\0\u1848\0\u1880\0\u18b8\0\u0118"+
    "\0\u18f0\0\u1928\0\70\0\70\0\70\0\70\0\70\0\70"+
    "\0\70\0\70\0\70\0\u1960\0\u1998\0\u19d0\0\70\0\u1a08"+
    "\0\u1a08\0\u0968\0\70\0\u1a40\0\70\0\70\0\u1a78\0\u1ab0"+
    "\0\u1ae8\0\u0118\0\u0118\0\u1b20\0\u1b58\0\u1b90\0\u1bc8\0\u0118"+
    "\0\u1c00\0\u1c38\0\u1c70\0\u1ca8\0\u1ce0\0\u1d18\0\u1d50\0\u1d88"+
    "\0\u1dc0\0\u1df8\0\u1e30\0\u1e68\0\u1ea0\0\u1ed8\0\u1f10\0\u0118"+
    "\0\u1f48\0\u1f80\0\u1fb8\0\u1ff0\0\u2028\0\u2060\0\u2098\0\u20d0"+
    "\0\u2108\0\u2140\0\u2178\0\u21b0\0\u21e8\0\u2220\0\70\0\u0118"+
    "\0\u0118\0\u0118\0\u0118\0\u2258\0\70\0\u2290\0\u22c8\0\u2300"+
    "\0\u2338\0\u0118\0\u2370\0\u23a8\0\u23e0\0\u2418\0\u2450\0\u2488"+
    "\0\u24c0\0\u0118\0\u24f8\0\u2530\0\u2568\0\u25a0\0\u25d8\0\u2610"+
    "\0\u2648\0\u2680\0\u26b8\0\u26f0\0\u2728\0\u2760\0\u2798\0\u27d0"+
    "\0\u2808\0\u0118\0\70\0\u0118\0\u2840\0\u2878\0\u28b0\0\u28e8"+
    "\0\u2920\0\u2958\0\u2990\0\u29c8\0\u1960\0\u2a00\0\u2a38\0\u2a70"+
    "\0\u2aa8\0\u2ae0\0\u2b18\0\70\0\u0118\0\u2b50\0\u0118\0\u2b88"+
    "\0\u2bc0\0\u0118\0\u2bf8\0\70\0\u0118\0\u2c30\0\u2c68\0\u2ca0"+
    "\0\u2cd8\0\u2d10\0\70\0\u0118\0\u2d48\0\u2d80\0\u2db8\0\u0118"+
    "\0\u2df0\0\u2e28\0\u2e60\0\u2e98\0\u2ed0\0\u2f08\0\70\0\u0118"+
    "\0\u2f40\0\u2f78\0\u2fb0\0\u2fe8\0\u0118\0\u3020\0\u3058\0\u3090"+
    "\0\70\0\u30c8\0\u3100\0\u3138\0\u3170\0\u0118\0\u31a8\0\u31e0"+
    "\0\u3218\0\u3250\0\u3288\0\u0118\0\u32c0\0\u32f8\0\u3330\0\u3368"+
    "\0\u0118\0\u33a0\0\u33d8\0\u3410\0\u3448\0\u3480\0\u34b8\0\u0118"+
    "\0\u0118\0\u34f0\0\u3528\0\70\0\u0118\0\u0118\0\u3560\0\u3598"+
    "\0\u35d0\0\u3608\0\70\0\u0118\0\u3640\0\u3678\0\u36b0\0\u36e8"+
    "\0\u3720\0\u3758\0\u3790\0\70\0\u0118\0\u0118\0\u37c8\0\u0118"+
    "\0\u3800\0\u3838\0\u3870\0\u0118\0\u38a8\0\u38e0\0\u3918\0\u3950"+
    "\0\70\0\u0118\0\u0118\0\u3988\0\70\0\u0118\0\u39c0\0\u39f8"+
    "\0\u3a30\0\u3a68\0\u3aa0\0\u3ad8\0\70\0\70\0\u3b10\0\u3b48"+
    "\0\u0118\0\u0118\0\u3b80\0\u3bb8\0\u3bf0\0\u3c28\0\u3c60\0\u3c98"+
    "\0\u3cd0\0\70\0\u0118\0\70\0\u0118\0\u0118\0\u0118\0\u3d08"+
    "\0\u3d40\0\u0118\0\u3d78\0\u0118\0\u3db0\0\u3de8\0\u0118\0\70"+
    "\0\u3e20\0\u3e58\0\u0118\0\u3e90\0\u3ec8\0\u0118\0\u0118\0\u0118"+
    "\0\70\0\u0118\0\u3f00\0\u3f38\0\u3f70\0\u3fa8\0\u0118\0\u0118"+
    "\0\u3fe0\0\u4018\0\u4050\0\u4088\0\70\0\70\0\u0118\0\u0118"+
    "\0\u40c0\0\70\0\u0118\0\u0118\0\u40f8\0\u4130\0\u4168\0\70"+
    "\0\u0118\0\u41a0\0\u41d8\0\70\0\u0118\0\u4210\0\70\0\u4248"+
    "\0\u0118\0\u0118\0\u4280\0\u42b8\0\u0118\0\u42f0\0\u4328\0\u4360"+
    "\0\u4398\0\u43d0\0\u4408\0\u0118\0\u4440\0\u0118\0\u4478\0\u0118"+
    "\0\70\0\u0118\0\u44b0\0\u44e8\0\70\0\u0118\0\70\0\u0118"+
    "\0\u4520\0\u4558\0\u4590\0\u45c8\0\u4600\0\u4638\0\u4670\0\u46a8"+
    "\0\u46e0\0\u4718\0\u4750\0\u4788\0\u47c0\0\u47f8\0\u4830\0\u4868"+
    "\0\70\0\u0118\0\u48a0\0\u48d8\0\u4910\0\u4948\0\u4980\0\u49b8"+
    "\0\u49f0\0\u4a28\0\u4a60\0\u4a98\0\70\0\u0118\0\u4ad0\0\u4b08"+
    "\0\70\0\u0118\0\u4b40\0\u4b78\0\u4bb0\0\u4be8\0\70\0\u0118"+
    "\0\70\0\u0118";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[482];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\3\1\7\1\10"+
    "\1\11\1\2\1\12\2\2\1\3\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\7\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\7\1\40\1\10\1\7\1\41"+
    "\1\7\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\74\0\1\57"+
    "\46\0\1\60\67\0\1\61\21\0\1\62\45\0\1\63"+
    "\23\0\3\7\1\64\6\0\11\7\1\0\20\7\25\0"+
    "\1\10\1\0\1\65\34\0\1\10\27\0\3\7\7\0"+
    "\11\7\1\0\20\7\15\0\13\66\1\67\1\70\53\66"+
    "\7\71\1\72\1\71\1\73\2\71\1\74\2\71\1\75"+
    "\1\71\11\72\1\71\14\72\1\71\3\72\15\71\22\0"+
    "\1\76\3\0\1\77\12\0\1\100\3\0\1\101\31\0"+
    "\3\7\1\64\6\0\1\7\1\102\3\7\1\103\3\7"+
    "\1\0\6\7\1\104\3\7\1\105\5\7\24\0\3\7"+
    "\1\64\6\0\2\7\1\106\6\7\1\0\1\7\1\107"+
    "\16\7\24\0\3\7\1\64\6\0\1\7\1\110\2\7"+
    "\1\111\1\7\1\112\2\7\1\0\3\7\1\113\14\7"+
    "\24\0\3\7\1\64\6\0\10\7\1\114\1\0\2\7"+
    "\1\115\1\116\4\7\1\117\7\7\24\0\3\7\1\64"+
    "\6\0\10\7\1\120\1\0\2\7\1\121\1\122\4\7"+
    "\1\123\7\7\24\0\3\7\1\64\5\0\1\124\1\125"+
    "\5\7\1\126\2\7\1\0\1\7\1\127\16\7\24\0"+
    "\3\7\1\64\6\0\1\7\1\130\6\7\1\131\1\132"+
    "\1\133\1\7\1\134\15\7\24\0\3\7\1\64\5\0"+
    "\1\135\1\136\1\7\1\137\6\7\1\0\1\7\1\140"+
    "\2\7\1\141\13\7\35\0\2\142\10\0\2\143\1\144"+
    "\42\0\3\7\1\64\5\0\1\142\1\145\10\7\1\143"+
    "\1\146\1\147\16\7\24\0\3\7\1\64\6\0\3\7"+
    "\1\150\1\7\1\151\2\7\1\152\1\0\3\7\1\153"+
    "\1\154\13\7\24\0\3\7\1\64\6\0\1\7\1\155"+
    "\2\7\1\156\1\7\1\157\2\7\1\160\1\161\17\7"+
    "\24\0\3\7\1\64\6\0\5\7\1\162\3\7\1\0"+
    "\1\7\1\163\1\164\15\7\24\0\3\7\1\64\6\0"+
    "\10\7\1\165\1\0\20\7\24\0\3\7\1\64\6\0"+
    "\5\7\1\166\3\7\1\0\2\7\1\167\15\7\24\0"+
    "\3\7\1\64\6\0\1\7\1\170\6\7\1\171\1\172"+
    "\1\173\17\7\24\0\3\7\1\64\6\0\11\7\1\174"+
    "\1\175\7\7\1\176\7\7\24\0\3\7\1\64\6\0"+
    "\10\7\1\177\1\0\20\7\24\0\3\7\1\64\6\0"+
    "\11\7\1\0\12\7\1\200\5\7\24\0\3\7\1\64"+
    "\6\0\11\7\1\0\2\7\1\201\15\7\24\0\3\7"+
    "\1\64\6\0\11\7\1\0\3\7\1\202\14\7\70\0"+
    "\1\203\67\0\1\204\1\205\66\0\1\206\67\0\1\207"+
    "\67\0\1\210\67\0\1\211\67\0\1\212\67\0\1\213"+
    "\14\0\4\214\1\215\63\214\1\62\1\216\1\217\65\62"+
    "\7\0\1\220\1\0\1\221\7\0\11\220\1\0\14\220"+
    "\1\0\3\220\25\0\1\222\36\0\1\222\20\0\1\66"+
    "\2\0\12\66\2\0\51\66\14\71\1\74\2\71\1\75"+
    "\57\71\3\72\2\71\1\74\2\71\1\223\1\71\11\72"+
    "\1\71\20\72\24\71\3\72\2\71\1\74\2\71\1\75"+
    "\1\71\11\72\1\71\20\72\16\71\2\0\12\71\2\0"+
    "\51\71\23\0\1\224\1\0\1\225\103\0\1\226\57\0"+
    "\1\227\56\0\2\230\55\0\3\7\1\64\6\0\2\7"+
    "\1\231\1\7\1\232\4\7\1\0\20\7\24\0\3\7"+
    "\1\64\6\0\11\7\1\0\6\7\1\233\11\7\24\0"+
    "\3\7\1\64\6\0\10\7\1\234\1\0\20\7\24\0"+
    "\3\7\1\64\5\0\1\230\1\235\10\7\1\0\20\7"+
    "\24\0\3\7\1\64\5\0\1\236\1\237\10\7\1\0"+
    "\20\7\24\0\3\7\1\64\6\0\7\7\1\240\1\7"+
    "\1\0\20\7\24\0\3\7\1\64\6\0\11\7\1\0"+
    "\1\7\1\241\3\7\1\242\12\7\24\0\3\7\1\64"+
    "\6\0\11\7\1\0\2\7\1\243\15\7\24\0\3\7"+
    "\1\64\6\0\10\7\1\244\1\0\20\7\24\0\3\7"+
    "\1\64\6\0\11\7\1\0\7\7\1\245\10\7\24\0"+
    "\3\7\1\64\5\0\1\246\1\247\10\7\1\0\20\7"+
    "\24\0\3\7\1\64\6\0\1\7\1\250\7\7\1\0"+
    "\20\7\24\0\3\7\1\64\6\0\5\7\1\251\3\7"+
    "\1\0\1\7\1\252\16\7\24\0\3\7\1\64\6\0"+
    "\11\7\1\0\3\7\1\253\14\7\24\0\3\7\1\64"+
    "\6\0\11\7\1\0\11\7\1\254\6\7\24\0\3\7"+
    "\1\64\6\0\11\7\1\255\1\256\17\7\24\0\2\7"+
    "\1\257\1\64\6\0\6\7\1\260\2\7\1\0\20\7"+
    "\24\0\3\7\1\64\6\0\1\7\1\261\7\7\1\0"+
    "\20\7\47\0\2\262\43\0\3\7\1\64\6\0\11\7"+
    "\1\262\1\263\17\7\24\0\3\7\1\64\6\0\6\7"+
    "\1\264\1\265\1\7\1\0\20\7\24\0\3\7\1\64"+
    "\6\0\11\7\1\266\1\267\17\7\24\0\3\7\1\64"+
    "\5\0\1\270\1\271\1\7\1\272\6\7\1\0\20\7"+
    "\24\0\3\7\1\64\6\0\4\7\1\273\4\7\1\0"+
    "\20\7\35\0\2\274\55\0\3\7\1\64\5\0\1\274"+
    "\1\275\10\7\1\0\20\7\24\0\3\7\1\64\6\0"+
    "\11\7\1\0\3\7\1\276\14\7\41\0\1\277\52\0"+
    "\3\7\1\64\6\0\3\7\1\300\5\7\1\0\20\7"+
    "\24\0\3\7\1\64\6\0\2\7\1\301\6\7\1\0"+
    "\20\7\24\0\3\7\1\64\6\0\7\7\1\302\1\7"+
    "\1\0\20\7\24\0\3\7\1\64\6\0\11\7\1\0"+
    "\13\7\1\303\4\7\51\0\1\304\73\0\1\305\47\0"+
    "\2\306\3\0\1\307\6\0\1\310\42\0\3\7\1\64"+
    "\6\0\11\7\1\0\1\7\1\311\16\7\24\0\3\7"+
    "\1\64\6\0\11\7\1\0\5\7\1\312\12\7\24\0"+
    "\3\7\1\64\5\0\1\306\1\313\3\7\1\314\4\7"+
    "\1\0\1\7\1\315\16\7\24\0\3\7\1\64\6\0"+
    "\11\7\1\0\10\7\1\316\7\7\24\0\3\7\1\64"+
    "\6\0\2\7\1\317\6\7\1\0\6\7\1\320\11\7"+
    "\24\0\3\7\1\64\6\0\4\7\1\321\4\7\1\0"+
    "\20\7\24\0\3\7\1\64\6\0\4\7\1\322\4\7"+
    "\1\0\20\7\24\0\3\7\1\64\6\0\2\7\1\323"+
    "\5\7\1\324\1\0\20\7\24\0\3\7\1\64\6\0"+
    "\6\7\1\325\2\7\1\0\20\7\24\0\3\7\1\64"+
    "\6\0\11\7\1\0\2\7\1\326\15\7\24\0\3\7"+
    "\1\64\6\0\10\7\1\327\1\0\20\7\63\0\1\330"+
    "\30\0\3\7\1\64\6\0\11\7\1\0\13\7\1\331"+
    "\4\7\24\0\3\7\1\64\6\0\4\7\1\332\4\7"+
    "\1\0\20\7\24\0\3\7\1\64\6\0\7\7\1\333"+
    "\1\7\1\0\20\7\24\0\3\7\1\64\6\0\2\7"+
    "\1\334\6\7\1\0\2\7\1\335\15\7\24\0\3\7"+
    "\1\64\6\0\2\7\1\336\6\7\1\0\20\7\24\0"+
    "\3\7\1\64\6\0\11\7\1\0\3\7\1\337\14\7"+
    "\24\0\3\7\1\64\6\0\11\7\1\0\2\7\1\340"+
    "\15\7\24\0\3\7\1\64\6\0\4\7\1\341\4\7"+
    "\1\0\17\7\1\342\51\0\1\343\42\0\3\7\1\64"+
    "\6\0\11\7\1\0\1\7\1\344\16\7\42\0\1\345"+
    "\51\0\3\7\1\64\6\0\4\7\1\346\4\7\1\0"+
    "\20\7\24\0\3\7\1\64\6\0\1\7\1\347\7\7"+
    "\1\0\20\7\24\0\3\7\1\64\6\0\11\7\1\0"+
    "\4\7\1\350\13\7\24\0\3\7\1\64\6\0\11\7"+
    "\1\0\3\7\1\351\14\7\24\0\3\7\1\64\6\0"+
    "\11\7\1\352\1\353\17\7\15\0\4\214\1\354\66\214"+
    "\1\355\1\354\63\214\2\0\1\217\74\0\3\220\7\0"+
    "\11\220\1\0\20\220\37\0\1\356\70\0\1\357\74\0"+
    "\1\360\46\0\3\7\1\64\6\0\1\7\1\361\7\7"+
    "\1\0\20\7\24\0\3\7\1\64\6\0\2\7\1\362"+
    "\6\7\1\0\20\7\24\0\3\7\1\64\6\0\7\7"+
    "\1\363\1\7\1\0\20\7\37\0\1\364\54\0\3\7"+
    "\1\64\6\0\1\7\1\365\7\7\1\0\20\7\24\0"+
    "\3\7\1\64\6\0\11\7\1\0\13\7\1\366\4\7"+
    "\24\0\3\7\1\64\6\0\4\7\1\367\4\7\1\0"+
    "\20\7\24\0\3\7\1\64\6\0\11\7\1\370\1\371"+
    "\17\7\24\0\3\7\1\64\6\0\7\7\1\372\1\7"+
    "\1\0\20\7\24\0\3\7\1\64\6\0\1\7\1\373"+
    "\7\7\1\0\20\7\37\0\1\374\54\0\3\7\1\64"+
    "\6\0\1\7\1\375\7\7\1\0\20\7\24\0\3\7"+
    "\1\64\6\0\10\7\1\376\1\0\20\7\24\0\3\7"+
    "\1\64\6\0\11\7\1\0\1\7\1\377\16\7\24\0"+
    "\3\7\1\64\6\0\3\7\1\u0100\5\7\1\0\20\7"+
    "\24\0\3\7\1\64\6\0\11\7\1\0\3\7\1\u0101"+
    "\14\7\24\0\3\7\1\64\6\0\2\7\1\u0102\6\7"+
    "\1\0\20\7\56\0\1\u0103\35\0\3\7\1\64\6\0"+
    "\11\7\1\0\6\7\1\u0104\11\7\24\0\3\7\1\64"+
    "\6\0\3\7\1\u0105\1\u0106\2\7\1\u0107\1\7\1\0"+
    "\20\7\24\0\3\7\1\64\6\0\11\7\1\0\1\7"+
    "\1\u0108\16\7\51\0\1\u0109\42\0\3\7\1\64\6\0"+
    "\11\7\1\0\1\7\1\u010a\16\7\24\0\3\7\1\64"+
    "\6\0\1\7\1\u010b\7\7\1\0\20\7\24\0\3\7"+
    "\1\64\6\0\10\7\1\u010c\1\0\20\7\53\0\1\u010d"+
    "\40\0\3\7\1\64\6\0\11\7\1\0\3\7\1\u010e"+
    "\14\7\41\0\1\u010f\52\0\3\7\1\64\6\0\3\7"+
    "\1\u0110\5\7\1\0\20\7\24\0\3\7\1\64\6\0"+
    "\1\7\1\u0111\7\7\1\0\20\7\24\0\3\7\1\64"+
    "\6\0\1\7\1\u0112\7\7\1\0\20\7\42\0\1\u0113"+
    "\51\0\3\7\1\64\6\0\4\7\1\u0114\4\7\1\0"+
    "\20\7\24\0\3\7\1\64\6\0\6\7\1\u0115\2\7"+
    "\1\0\20\7\43\0\1\u0116\63\0\1\u0117\2\0\1\u0118"+
    "\100\0\1\u0119\53\0\1\u011a\54\0\3\7\1\64\6\0"+
    "\5\7\1\u011b\3\7\1\0\20\7\24\0\3\7\1\64"+
    "\6\0\1\7\1\u011c\2\7\1\u011d\4\7\1\0\20\7"+
    "\24\0\3\7\1\64\6\0\11\7\1\0\3\7\1\u011e"+
    "\14\7\24\0\3\7\1\64\6\0\1\7\1\u011f\7\7"+
    "\1\0\20\7\24\0\3\7\1\64\6\0\10\7\1\u0120"+
    "\1\0\20\7\24\0\3\7\1\64\6\0\2\7\1\u0121"+
    "\6\7\1\0\20\7\24\0\3\7\1\64\6\0\11\7"+
    "\1\0\11\7\1\u0122\6\7\24\0\3\7\1\64\6\0"+
    "\5\7\1\u0123\3\7\1\0\20\7\24\0\3\7\1\64"+
    "\6\0\11\7\1\0\14\7\1\u0124\3\7\24\0\3\7"+
    "\1\64\6\0\11\7\1\0\2\7\1\u0125\15\7\24\0"+
    "\3\7\1\64\6\0\2\7\1\u0126\6\7\1\0\20\7"+
    "\24\0\3\7\1\64\6\0\11\7\1\u0127\1\u0128\17\7"+
    "\24\0\3\7\1\64\6\0\7\7\1\u0129\1\7\1\0"+
    "\20\7\60\0\1\u012a\33\0\3\7\1\64\6\0\11\7"+
    "\1\0\10\7\1\u012b\7\7\24\0\3\7\1\64\6\0"+
    "\1\7\1\u012c\7\7\1\0\20\7\24\0\3\7\1\64"+
    "\6\0\1\7\1\u012d\7\7\1\0\20\7\24\0\3\7"+
    "\1\64\6\0\5\7\1\u012e\3\7\1\0\20\7\24\0"+
    "\3\7\1\64\6\0\3\7\1\u012f\5\7\1\0\20\7"+
    "\24\0\3\7\1\64\6\0\2\7\1\u0130\6\7\1\0"+
    "\20\7\24\0\3\7\1\64\6\0\11\7\1\0\6\7"+
    "\1\u0131\11\7\24\0\3\7\1\64\6\0\11\7\1\0"+
    "\13\7\1\u0132\4\7\24\0\3\7\1\64\6\0\3\7"+
    "\1\u0133\5\7\1\0\20\7\60\0\1\u0134\33\0\3\7"+
    "\1\64\6\0\11\7\1\0\10\7\1\u0135\7\7\24\0"+
    "\3\7\1\64\6\0\11\7\1\0\1\7\1\u0136\1\u0137"+
    "\15\7\24\0\3\7\1\64\6\0\11\7\1\u0138\1\u0139"+
    "\17\7\24\0\3\7\1\64\6\0\5\7\1\u013a\3\7"+
    "\1\0\20\7\51\0\1\u013b\42\0\3\7\1\64\6\0"+
    "\11\7\1\0\1\7\1\u013c\16\7\15\0\3\214\1\217"+
    "\1\354\63\214\24\0\1\u013d\66\0\1\u013e\75\0\1\u013f"+
    "\45\0\3\7\1\64\6\0\3\7\1\u0140\5\7\1\0"+
    "\20\7\24\0\3\7\1\64\6\0\2\7\1\u0141\6\7"+
    "\1\0\20\7\24\0\3\7\1\64\6\0\10\7\1\u0142"+
    "\1\0\20\7\24\0\3\7\1\64\6\0\4\7\1\u0143"+
    "\4\7\1\0\20\7\56\0\1\u0144\35\0\3\7\1\64"+
    "\6\0\11\7\1\0\6\7\1\u0145\11\7\24\0\3\7"+
    "\1\64\6\0\11\7\1\0\2\7\1\u0146\15\7\24\0"+
    "\3\7\1\64\6\0\4\7\1\u0147\4\7\1\0\20\7"+
    "\24\0\3\7\1\64\6\0\4\7\1\u0148\4\7\1\0"+
    "\20\7\24\0\3\7\1\64\6\0\10\7\1\u0149\1\0"+
    "\20\7\24\0\3\7\1\64\5\0\1\u014a\1\u014b\10\7"+
    "\1\0\20\7\24\0\3\7\1\64\6\0\1\7\1\u014c"+
    "\7\7\1\0\20\7\24\0\3\7\1\64\6\0\11\7"+
    "\1\0\10\7\1\u014d\7\7\24\0\3\7\1\64\6\0"+
    "\11\7\1\u014e\1\u014f\17\7\24\0\3\7\1\64\6\0"+
    "\10\7\1\u0150\1\0\20\7\63\0\1\u0151\30\0\3\7"+
    "\1\64\6\0\11\7\1\0\13\7\1\u0152\4\7\24\0"+
    "\3\7\1\64\6\0\11\7\1\0\2\7\1\u0153\15\7"+
    "\24\0\3\7\1\64\6\0\4\7\1\u0154\4\7\1\0"+
    "\20\7\51\0\1\u0155\42\0\3\7\1\64\6\0\11\7"+
    "\1\0\1\7\1\u0156\16\7\24\0\3\7\1\64\6\0"+
    "\4\7\1\u0157\4\7\1\0\20\7\24\0\3\7\1\64"+
    "\6\0\4\7\1\u0158\4\7\1\0\20\7\47\0\2\u0159"+
    "\43\0\3\7\1\64\6\0\11\7\1\u0159\1\u015a\17\7"+
    "\40\0\1\u015b\101\0\1\u015c\67\0\1\u015d\67\0\1\u015e"+
    "\41\0\3\7\1\64\6\0\2\7\1\u015f\6\7\1\0"+
    "\20\7\24\0\3\7\1\64\6\0\11\7\1\0\2\7"+
    "\1\u0160\15\7\24\0\3\7\1\64\6\0\11\7\1\0"+
    "\2\7\1\u0161\15\7\24\0\3\7\1\64\6\0\11\7"+
    "\1\0\2\7\1\u0162\15\7\24\0\3\7\1\64\6\0"+
    "\11\7\1\0\2\7\1\u0163\15\7\24\0\3\7\1\64"+
    "\6\0\11\7\1\u0164\1\u0165\17\7\24\0\3\7\1\64"+
    "\6\0\1\7\1\u0166\7\7\1\0\20\7\24\0\3\7"+
    "\1\64\6\0\11\7\1\0\2\7\1\u0167\15\7\24\0"+
    "\3\7\1\64\6\0\3\7\1\u0168\5\7\1\0\20\7"+
    "\24\0\3\7\1\64\6\0\10\7\1\u0169\1\0\20\7"+
    "\56\0\1\u016a\35\0\3\7\1\64\6\0\11\7\1\0"+
    "\6\7\1\u016b\11\7\42\0\1\u016c\51\0\3\7\1\64"+
    "\6\0\4\7\1\u016d\4\7\1\0\20\7\24\0\3\7"+
    "\1\64\6\0\11\7\1\0\2\7\1\u016e\15\7\24\0"+
    "\3\7\1\64\6\0\11\7\1\0\2\7\1\u016f\15\7"+
    "\24\0\3\7\1\64\6\0\1\7\1\u0170\7\7\1\0"+
    "\20\7\24\0\3\7\1\64\6\0\11\7\1\0\10\7"+
    "\1\u0171\7\7\24\0\3\7\1\64\6\0\1\7\1\u0172"+
    "\7\7\1\0\20\7\24\0\3\7\1\64\6\0\11\7"+
    "\1\0\10\7\1\u0173\7\7\24\0\3\7\1\64\6\0"+
    "\1\7\1\u0174\7\7\1\0\20\7\51\0\1\u0175\42\0"+
    "\3\7\1\64\6\0\11\7\1\0\1\7\1\u0176\16\7"+
    "\24\0\3\7\1\64\6\0\6\7\1\u0177\2\7\1\0"+
    "\20\7\42\0\1\u0178\74\0\2\u0179\61\0\1\u017a\51\0"+
    "\3\7\1\64\6\0\4\7\1\u017b\4\7\1\0\20\7"+
    "\24\0\3\7\1\64\6\0\11\7\1\u0179\1\u017c\17\7"+
    "\24\0\3\7\1\64\6\0\4\7\1\u017d\4\7\1\0"+
    "\20\7\24\0\3\7\1\64\6\0\11\7\1\0\10\7"+
    "\1\u017e\7\7\24\0\3\7\1\64\6\0\1\7\1\u017f"+
    "\7\7\1\0\20\7\24\0\3\7\1\64\6\0\4\7"+
    "\1\u0180\4\7\1\0\20\7\37\0\1\u0181\54\0\3\7"+
    "\1\64\6\0\1\7\1\u0182\7\7\1\0\20\7\24\0"+
    "\3\7\1\64\6\0\10\7\1\u0183\1\0\20\7\56\0"+
    "\1\u0184\35\0\3\7\1\64\6\0\11\7\1\0\6\7"+
    "\1\u0185\11\7\24\0\3\7\1\64\6\0\4\7\1\u0186"+
    "\4\7\1\0\20\7\24\0\3\7\1\64\6\0\1\7"+
    "\1\u0187\7\7\1\0\20\7\24\0\3\7\1\64\6\0"+
    "\1\7\1\u0188\7\7\1\0\20\7\24\0\3\7\1\64"+
    "\6\0\11\7\1\u0189\1\u018a\17\7\51\0\1\u018b\42\0"+
    "\3\7\1\64\6\0\11\7\1\0\1\7\1\u018c\16\7"+
    "\40\0\1\u018d\71\0\1\u018e\51\0\3\7\1\64\6\0"+
    "\2\7\1\u018f\6\7\1\0\20\7\24\0\3\7\1\64"+
    "\6\0\4\7\1\u0190\4\7\1\0\20\7\24\0\2\7"+
    "\1\u0191\1\64\6\0\11\7\1\0\20\7\55\0\1\u0192"+
    "\36\0\3\7\1\64\6\0\11\7\1\0\5\7\1\u0193"+
    "\12\7\24\0\3\7\1\64\6\0\11\7\1\0\2\7"+
    "\1\u0194\15\7\24\0\3\7\1\64\6\0\10\7\1\u0195"+
    "\1\0\20\7\24\0\3\7\1\64\6\0\11\7\1\0"+
    "\10\7\1\u0196\7\7\24\0\3\7\1\64\6\0\3\7"+
    "\1\u0197\5\7\1\0\20\7\24\0\3\7\1\64\5\0"+
    "\1\u0198\1\u0199\10\7\1\0\20\7\24\0\3\7\1\64"+
    "\6\0\10\7\1\u019a\1\0\20\7\24\0\3\7\1\64"+
    "\6\0\1\7\1\u019b\7\7\1\0\20\7\63\0\1\u019c"+
    "\30\0\3\7\1\64\6\0\11\7\1\0\13\7\1\u019d"+
    "\4\7\51\0\1\u019e\55\0\1\u019f\54\0\3\7\1\64"+
    "\6\0\11\7\1\0\1\7\1\u01a0\16\7\24\0\3\7"+
    "\1\64\6\0\1\7\1\u01a1\7\7\1\0\20\7\24\0"+
    "\3\7\1\64\6\0\11\7\1\0\2\7\1\u01a2\15\7"+
    "\37\0\1\u01a3\54\0\3\7\1\64\6\0\1\7\1\u01a4"+
    "\7\7\1\0\20\7\24\0\3\7\1\64\6\0\1\7"+
    "\1\u01a5\7\7\1\0\20\7\56\0\1\u01a6\35\0\3\7"+
    "\1\64\6\0\11\7\1\0\6\7\1\u01a7\11\7\41\0"+
    "\1\u01a8\52\0\3\7\1\64\6\0\3\7\1\u01a9\5\7"+
    "\1\0\20\7\24\0\3\7\1\64\5\0\1\u01aa\1\u01ab"+
    "\10\7\1\0\20\7\24\0\3\7\1\64\6\0\2\7"+
    "\1\u01ac\6\7\1\0\20\7\24\0\3\7\1\64\6\0"+
    "\10\7\1\u01ad\1\0\20\7\24\0\3\7\1\64\6\0"+
    "\1\7\1\u01ae\7\7\1\0\20\7\24\0\3\7\1\64"+
    "\6\0\11\7\1\0\2\7\1\u01af\15\7\24\0\3\7"+
    "\1\64\6\0\7\7\1\u01b0\1\7\1\0\20\7\42\0"+
    "\1\u01b1\51\0\3\7\1\64\6\0\4\7\1\u01b2\4\7"+
    "\1\0\20\7\35\0\2\u01b3\55\0\3\7\1\64\5\0"+
    "\1\u01b3\1\u01b4\10\7\1\0\20\7\37\0\1\u01b5\54\0"+
    "\3\7\1\64\6\0\1\7\1\u01b6\7\7\1\0\20\7"+
    "\42\0\1\u01b7\51\0\3\7\1\64\6\0\4\7\1\u01b8"+
    "\4\7\1\0\20\7\47\0\2\u01b9\43\0\3\7\1\64"+
    "\6\0\11\7\1\u01b9\1\u01ba\17\7\24\0\3\7\1\64"+
    "\6\0\11\7\1\0\2\7\1\u01bb\15\7\24\0\3\7"+
    "\1\64\5\0\1\u01bc\1\u01bd\10\7\1\0\14\7\1\u01be"+
    "\3\7\42\0\1\u01bf\51\0\3\7\1\64\6\0\4\7"+
    "\1\u01c0\4\7\1\0\20\7\65\0\1\u01c1\26\0\3\7"+
    "\1\64\6\0\11\7\1\0\15\7\1\u01c2\2\7\24\0"+
    "\2\7\1\u01c3\1\64\6\0\11\7\1\0\20\7\47\0"+
    "\2\u01c4\43\0\3\7\1\64\6\0\11\7\1\u01c4\1\u01c5"+
    "\17\7\24\0\2\7\1\u01c6\1\64\6\0\11\7\1\0"+
    "\20\7\46\0\1\u01c7\45\0\3\7\1\64\6\0\10\7"+
    "\1\u01c8\1\0\20\7\37\0\1\u01c9\54\0\3\7\1\64"+
    "\6\0\1\7\1\u01ca\7\7\1\0\20\7\24\0\3\7"+
    "\1\64\5\0\1\u01cb\1\u01cc\10\7\1\0\20\7\65\0"+
    "\1\u01cd\26\0\3\7\1\64\6\0\11\7\1\0\15\7"+
    "\1\u01ce\2\7\24\0\3\7\1\64\5\0\1\u01cf\1\u01d0"+
    "\10\7\1\0\20\7\56\0\1\u01d1\35\0\3\7\1\64"+
    "\6\0\11\7\1\0\6\7\1\u01d2\11\7\47\0\2\u01d3"+
    "\43\0\3\7\1\64\6\0\11\7\1\u01d3\1\u01d4\17\7"+
    "\37\0\1\u01d5\54\0\3\7\1\64\6\0\1\7\1\u01d6"+
    "\7\7\1\0\20\7\47\0\2\u01d7\43\0\3\7\1\64"+
    "\6\0\11\7\1\u01d7\1\u01d8\17\7\44\0\1\u01d9\47\0"+
    "\3\7\1\64\6\0\6\7\1\u01da\2\7\1\0\20\7"+
    "\65\0\1\u01db\26\0\3\7\1\64\6\0\11\7\1\0"+
    "\15\7\1\u01dc\2\7\65\0\1\u01dd\26\0\3\7\1\64"+
    "\6\0\11\7\1\0\15\7\1\u01de\2\7\37\0\1\u01df"+
    "\54\0\3\7\1\64\6\0\1\7\1\u01e0\7\7\1\0"+
    "\20\7\37\0\1\u01e1\54\0\3\7\1\64\6\0\1\7"+
    "\1\u01e2\7\7\1\0\20\7\15\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[19488];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\36\1\1\11\10\1\4\11\1\0\2\11"+
    "\1\1\1\11\3\0\1\11\5\0\1\11\4\0\22\1"+
    "\1\0\5\1\1\0\10\1\1\0\14\1\1\0\11\1"+
    "\1\0\1\1\1\0\6\1\11\11\2\0\1\1\1\11"+
    "\1\1\1\0\1\1\1\11\1\0\2\11\2\0\5\1"+
    "\1\0\7\1\1\0\6\1\1\0\4\1\1\0\3\1"+
    "\1\0\1\1\1\0\3\1\1\0\2\1\1\11\4\1"+
    "\1\0\1\11\1\0\1\1\1\0\17\1\1\0\12\1"+
    "\1\11\1\1\1\0\4\1\1\0\1\1\1\0\1\1"+
    "\3\0\3\1\1\11\3\1\1\0\3\1\1\11\6\1"+
    "\1\11\5\1\1\0\3\1\1\0\1\1\1\11\3\1"+
    "\1\0\2\1\3\0\1\11\1\0\14\1\1\0\2\1"+
    "\1\0\11\1\1\11\3\1\1\0\2\1\1\11\1\1"+
    "\3\0\4\1\1\11\5\1\1\0\3\1\1\0\2\1"+
    "\1\11\3\1\1\11\3\1\1\0\1\1\2\0\2\11"+
    "\5\1\1\0\5\1\1\11\1\1\1\11\10\1\1\0"+
    "\2\1\1\11\2\0\6\1\1\11\2\1\1\0\4\1"+
    "\1\0\1\1\1\0\1\1\2\11\3\1\1\11\5\1"+
    "\1\11\3\1\1\11\1\1\1\0\1\11\3\1\1\0"+
    "\2\1\1\0\1\1\1\0\1\1\1\0\6\1\1\11"+
    "\1\1\1\0\1\1\1\11\1\1\1\11\1\1\1\0"+
    "\2\1\1\0\2\1\1\0\1\1\1\0\2\1\1\0"+
    "\2\1\1\0\1\1\1\11\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\11"+
    "\1\1\1\0\1\1\1\11\1\1\1\0\1\1\1\0"+
    "\1\1\1\11\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[482];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	// Initialize any necessary variables here
	
	// A table I will create to store Lexical Errors found | import library for LinkedList
	public LinkedList<TError> TableLE = new LinkedList<TError>();
	public LinkedList<String> StmtCopy = new LinkedList<String>(); // DELETE THIS, will be replaced by PrettyfiedStatement
	
	public LinkedList<PrettyStatement> PrettyfiedStatement = new LinkedList<PrettyStatement>();
	
		
	// Will need to create a structure to save the lexeme and its corresponding category code.
	public void prettyfier (String lexeme, int category) {
		
		PrettyStatement ps = new PrettyStatement(lexeme,category);
		PrettyfiedStatement.add(ps);
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public JFlex_Rules_SQL(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 234) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("\n### Lexical error (Illegal element) ### - '" + yytext() + "' line: " + yyline + ", column: " + yychar + "\n"); 
				  	  TError errors_found = new TError(yytext(),yyline,yycolumn,"Lexical Error","Unrecognized symbol.");
				  	  TableLE.add(errors_found); 
				  	  prettyfier(yytext(), Categories.ERROR);
					  return new Symbol(sym.ILLEGAL_CHAR, yyline, yycolumn, yytext());
            }
          case 119: break;
          case 2: 
            { System.out.println("Recognized space: " + yytext()); prettyfier(yytext(), Categories.NOTHING );
            }
          case 120: break;
          case 3: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._DIVIDE, yyline+1, yycolumn+1, yytext());
            }
          case 121: break;
          case 4: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._STAR, yyline+1, yycolumn+1, yytext());
            }
          case 122: break;
          case 5: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._MINUS, yyline+1, yycolumn+1, yytext());
            }
          case 123: break;
          case 6: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.IDENTIFIER); return new Symbol(sym.IDENTIFIER, yyline+1, yycolumn+1, yytext());
            }
          case 124: break;
          case 7: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NUMBER); return new Symbol(sym.INTEGER, yyline+1, yycolumn+1, yytext());
            }
          case 125: break;
          case 8: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._EQU, yyline+1, yycolumn+1, yytext());
            }
          case 126: break;
          case 9: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._GT, yyline+1, yycolumn+1, yytext());
            }
          case 127: break;
          case 10: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._LT, yyline+1, yycolumn+1, yytext());
            }
          case 128: break;
          case 11: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._PLUS, yyline+1, yycolumn+1, yytext());
            }
          case 129: break;
          case 12: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._OPENPAR, yyline+1, yycolumn+1, yytext());
            }
          case 130: break;
          case 13: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._CLOSEPAR, yyline+1, yycolumn+1, yytext());
            }
          case 131: break;
          case 14: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._SEMCOL2, yyline+1, yycolumn+1, yytext());
            }
          case 132: break;
          case 15: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._COMMA, yyline+1, yycolumn+1, yytext());
            }
          case 133: break;
          case 16: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._DIVIDEEQ, yyline+1, yycolumn+1, yytext());
            }
          case 134: break;
          case 17: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._TIMESEQ, yyline+1, yycolumn+1, yytext());
            }
          case 135: break;
          case 18: 
            { System.out.println("Recognized comment: " + yytext()); prettyfier(yytext(), Categories.COMMENT );
            }
          case 136: break;
          case 19: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._MINUSEQ, yyline+1, yycolumn+1, yytext());
            }
          case 137: break;
          case 20: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.LITERAL_STRING); return new Symbol(sym.LITERAL_STRING, yyline+1, yycolumn+1, yytext());
            }
          case 138: break;
          case 21: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.IDENTIFIER); return new Symbol(sym.QCOLALIAS, yyline+1, yycolumn+1, yytext());
            }
          case 139: break;
          case 22: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.AS, yyline+1, yycolumn+1, yytext());
            }
          case 140: break;
          case 23: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.IS, yyline+1, yycolumn+1, yytext());
            }
          case 141: break;
          case 24: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.IN, yyline+1, yycolumn+1, yytext());
            }
          case 142: break;
          case 25: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.ON, yyline+1, yycolumn+1, yytext());
            }
          case 143: break;
          case 26: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym._OR, yyline+1, yycolumn+1, yytext());
            }
          case 144: break;
          case 27: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.BY, yyline+1, yycolumn+1, yytext());
            }
          case 145: break;
          case 28: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._GET, yyline+1, yycolumn+1, yytext());
            }
          case 146: break;
          case 29: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._LET, yyline+1, yycolumn+1, yytext());
            }
          case 147: break;
          case 30: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._DIFF, yyline+1, yycolumn+1, yytext());
            }
          case 148: break;
          case 31: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._DIFF2, yyline+1, yycolumn+1, yytext());
            }
          case 149: break;
          case 32: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._PLUSEQ, yyline+1, yycolumn+1, yytext());
            }
          case 150: break;
          case 33: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._MODEQ, yyline+1, yycolumn+1, yytext());
            }
          case 151: break;
          case 34: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._ANDEQ, yyline+1, yycolumn+1, yytext());
            }
          case 152: break;
          case 35: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._POWEQ, yyline+1, yycolumn+1, yytext());
            }
          case 153: break;
          case 36: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NOTHING ); return new Symbol(sym._OREQ, yyline+1, yycolumn+1, yytext());
            }
          case 154: break;
          case 37: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.IDENTIFIER); return new Symbol(sym.TABDOTCOL, yyline+1, yycolumn+1, yytext());
            }
          case 155: break;
          case 38: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.NUMBER); return new Symbol(sym.REAL, yyline+1, yycolumn+1, yytext());
            }
          case 156: break;
          case 39: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.IDENTIFIER); return new Symbol(sym.QTABLENAME, yyline+1, yycolumn+1, yytext());
            }
          case 157: break;
          case 40: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.SET, yyline+1, yycolumn+1, yytext());
            }
          case 158: break;
          case 41: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.SUM, yyline+1, yycolumn+1, yytext());
            }
          case 159: break;
          case 42: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.END, yyline+1, yycolumn+1, yytext());
            }
          case 160: break;
          case 43: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.TOP, yyline+1, yycolumn+1, yytext());
            }
          case 161: break;
          case 44: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.ASC, yyline+1, yycolumn+1, yytext());
            }
          case 162: break;
          case 45: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.ALL, yyline+1, yycolumn+1, yytext());
            }
          case 163: break;
          case 46: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym._AND, yyline+1, yycolumn+1, yytext());
            }
          case 164: break;
          case 47: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.AVG, yyline+1, yycolumn+1, yytext());
            }
          case 165: break;
          case 48: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.IIF, yyline+1, yycolumn+1, yytext());
            }
          case 166: break;
          case 49: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.INT, yyline+1, yycolumn+1, yytext());
            }
          case 167: break;
          case 50: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.NOT, yyline+1, yycolumn+1, yytext());
            }
          case 168: break;
          case 51: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.NVL, yyline+1, yycolumn+1, yytext());
            }
          case 169: break;
          case 52: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.MAX, yyline+1, yycolumn+1, yytext());
            }
          case 170: break;
          case 53: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.MIN, yyline+1, yycolumn+1, yytext());
            }
          case 171: break;
          case 54: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.ELSE, yyline+1, yycolumn+1, yytext());
            }
          case 172: break;
          case 55: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.LEFT, yyline+1, yycolumn+1, yytext());
            }
          case 173: break;
          case 56: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.LPAD, yyline+1, yycolumn+1, yytext());
            }
          case 174: break;
          case 57: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.CASE, yyline+1, yycolumn+1, yytext());
            }
          case 175: break;
          case 58: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.TRIM, yyline+1, yycolumn+1, yytext());
            }
          case 176: break;
          case 59: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.THEN, yyline+1, yycolumn+1, yytext());
            }
          case 177: break;
          case 60: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.DESC, yyline+1, yycolumn+1, yytext());
            }
          case 178: break;
          case 61: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.DATE, yyline+1, yycolumn+1, yytext());
            }
          case 179: break;
          case 62: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.DROP, yyline+1, yycolumn+1, yytext());
            }
          case 180: break;
          case 63: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.INTO, yyline+1, yycolumn+1, yytext());
            }
          case 181: break;
          case 64: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.NULL, yyline+1, yycolumn+1, yytext());
            }
          case 182: break;
          case 65: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.NVL2, yyline+1, yycolumn+1, yytext());
            }
          case 183: break;
          case 66: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.RPAD, yyline+1, yycolumn+1, yytext());
            }
          case 184: break;
          case 67: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.FULL, yyline+1, yycolumn+1, yytext());
            }
          case 185: break;
          case 68: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.FROM, yyline+1, yycolumn+1, yytext());
            }
          case 186: break;
          case 69: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.WITH, yyline+1, yycolumn+1, yytext());
            }
          case 187: break;
          case 70: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.WHEN, yyline+1, yycolumn+1, yytext());
            }
          case 188: break;
          case 71: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.JOIN, yyline+1, yycolumn+1, yytext());
            }
          case 189: break;
          case 72: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.LTRIM, yyline+1, yycolumn+1, yytext());
            }
          case 190: break;
          case 73: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.LOWER, yyline+1, yycolumn+1, yytext());
            }
          case 191: break;
          case 74: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.COUNT, yyline+1, yycolumn+1, yytext());
            }
          case 192: break;
          case 75: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.TABLE, yyline+1, yycolumn+1, yytext());
            }
          case 193: break;
          case 76: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.USING, yyline+1, yycolumn+1, yytext());
            }
          case 194: break;
          case 77: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.UPPER, yyline+1, yycolumn+1, yytext());
            }
          case 195: break;
          case 78: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.UNION, yyline+1, yycolumn+1, yytext());
            }
          case 196: break;
          case 79: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.INSTR, yyline+1, yycolumn+1, yytext());
            }
          case 197: break;
          case 80: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.INNER, yyline+1, yycolumn+1, yytext());
            }
          case 198: break;
          case 81: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.NCHAR, yyline+1, yycolumn+1, yytext());
            }
          case 199: break;
          case 82: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.RTRIM, yyline+1, yycolumn+1, yytext());
            }
          case 200: break;
          case 83: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.RIGHT, yyline+1, yycolumn+1, yytext());
            }
          case 201: break;
          case 84: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.OUTER, yyline+1, yycolumn+1, yytext());
            }
          case 202: break;
          case 85: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.ORDER, yyline+1, yycolumn+1, yytext());
            }
          case 203: break;
          case 86: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.MERGE, yyline+1, yycolumn+1, yytext());
            }
          case 204: break;
          case 87: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.WHERE, yyline+1, yycolumn+1, yytext());
            }
          case 205: break;
          case 88: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.GROUP, yyline+1, yycolumn+1, yytext());
            }
          case 206: break;
          case 89: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.SELECT, yyline+1, yycolumn+1, yytext());
            }
          case 207: break;
          case 90: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.LENGTH, yyline+1, yycolumn+1, yytext());
            }
          case 208: break;
          case 91: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.CREATE, yyline+1, yycolumn+1, yytext());
            }
          case 209: break;
          case 92: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.CONCAT, yyline+1, yycolumn+1, yytext());
            }
          case 210: break;
          case 93: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.CHOOSE, yyline+1, yycolumn+1, yytext());
            }
          case 211: break;
          case 94: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.UPDATE, yyline+1, yycolumn+1, yytext());
            }
          case 212: break;
          case 95: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.DELETE, yyline+1, yycolumn+1, yytext());
            }
          case 213: break;
          case 96: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.ISNULL, yyline+1, yycolumn+1, yytext());
            }
          case 214: break;
          case 97: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.INSERT, yyline+1, yycolumn+1, yytext());
            }
          case 215: break;
          case 98: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.NULLIF, yyline+1, yycolumn+1, yytext());
            }
          case 216: break;
          case 99: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.NUMBER, yyline+1, yycolumn+1, yytext());
            }
          case 217: break;
          case 100: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.VALUES, yyline+1, yycolumn+1, yytext());
            }
          case 218: break;
          case 101: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.HAVING, yyline+1, yycolumn+1, yytext());
            }
          case 219: break;
          case 102: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.SYSDATE, yyline+1, yycolumn+1, yytext());
            }
          case 220: break;
          case 103: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.TO_CHAR, yyline+1, yycolumn+1, yytext());
            }
          case 221: break;
          case 104: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.TO_DATE, yyline+1, yycolumn+1, yytext());
            }
          case 222: break;
          case 105: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.NATURAL, yyline+1, yycolumn+1, yytext());
            }
          case 223: break;
          case 106: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.REPLACE, yyline+1, yycolumn+1, yytext());
            }
          case 224: break;
          case 107: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.VARCHAR, yyline+1, yycolumn+1, yytext());
            }
          case 225: break;
          case 108: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.MATCHED, yyline+1, yycolumn+1, yytext());
            }
          case 226: break;
          case 109: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.SMALLINT, yyline+1, yycolumn+1, yytext());
            }
          case 227: break;
          case 110: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.DATETIME, yyline+1, yycolumn+1, yytext());
            }
          case 228: break;
          case 111: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.DISTINCT, yyline+1, yycolumn+1, yytext());
            }
          case 229: break;
          case 112: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.NVARCHAR, yyline+1, yycolumn+1, yytext());
            }
          case 230: break;
          case 113: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.VARCHAR2, yyline+1, yycolumn+1, yytext());
            }
          case 231: break;
          case 114: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.NCHAR_SIZE, yyline+1, yycolumn+1, yytext());
            }
          case 232: break;
          case 115: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.VARCHARSIZE, yyline+1, yycolumn+1, yytext());
            }
          case 233: break;
          case 116: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.TO_TIMESTAMP, yyline+1, yycolumn+1, yytext());
            }
          case 234: break;
          case 117: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.NVARCHAR_SIZE, yyline+1, yycolumn+1, yytext());
            }
          case 235: break;
          case 118: 
            { System.out.println("Recognized: " + yytext()); prettyfier(yytext(), Categories.RESERVED); return new Symbol(sym.VARCHAR2_SIZE, yyline+1, yycolumn+1, yytext());
            }
          case 236: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
