
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package com.kerberus.model.syntaxValidator.rules.sql;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 28;
  public static final int LEFT = 19;
  public static final int IDENTIFIER = 63;
  public static final int REAL = 65;
  public static final int FROM = 6;
  public static final int LTRIM = 42;
  public static final int _GT = 71;
  public static final int GROUP = 8;
  public static final int OUTER = 22;
  public static final int NATURAL = 18;
  public static final int _DIFF2 = 76;
  public static final int RIGHT = 20;
  public static final int TABLE = 14;
  public static final int SYSDATE = 26;
  public static final int _PLUSEQ = 82;
  public static final int SUM = 34;
  public static final int NVL = 51;
  public static final int JOIN = 24;
  public static final int INNER = 23;
  public static final int TO_DATE = 55;
  public static final int _LT = 72;
  public static final int INTEGER = 64;
  public static final int _CLOSEPAR = 91;
  public static final int NOT = 11;
  public static final int _OPENPAR = 90;
  public static final int MIN = 36;
  public static final int THEN = 59;
  public static final int _MINUSEQ = 83;
  public static final int LITERAL_STRING = 66;
  public static final int ISNULL = 54;
  public static final int TRIM = 46;
  public static final int LOWER = 48;
  public static final int WHEN = 58;
  public static final int INTO = 17;
  public static final int SELECT = 2;
  public static final int _AND = 80;
  public static final int FULL = 21;
  public static final int _POWEQ = 88;
  public static final int _DIVIDE = 79;
  public static final int _SEMCOL2 = 94;
  public static final int _LET = 73;
  public static final int IIF = 50;
  public static final int NULLIF = 53;
  public static final int DELETE = 5;
  public static final int TABDOTCOL = 68;
  public static final int QCOLALIAS = 69;
  public static final int _MINUS = 78;
  public static final int MATCHED = 62;
  public static final int _PLUS = 77;
  public static final int MAX = 35;
  public static final int LPAD = 38;
  public static final int CONCAT = 41;
  public static final int ELSE = 60;
  public static final int _MODEQ = 86;
  public static final int TO_TIMESTAMP = 27;
  public static final int INSTR = 44;
  public static final int _GET = 74;
  public static final int LENGTH = 40;
  public static final int AVG = 37;
  public static final int NULL = 32;
  public static final int EOF = 0;
  public static final int _STAR = 93;
  public static final int WHERE = 7;
  public static final int COUNT = 33;
  public static final int CHOOSE = 49;
  public static final int IS = 10;
  public static final int _EQU = 70;
  public static final int RPAD = 39;
  public static final int NVL2 = 52;
  public static final int IN = 30;
  public static final int SET = 4;
  public static final int error = 1;
  public static final int _OR = 81;
  public static final int ON = 29;
  public static final int END = 61;
  public static final int REPLACE = 45;
  public static final int BY = 15;
  public static final int QTABLENAME = 67;
  public static final int USING = 25;
  public static final int MERGE = 16;
  public static final int _ANDEQ = 87;
  public static final int _TIMESEQ = 84;
  public static final int _DIFF = 75;
  public static final int CASE = 57;
  public static final int _DIVIDEEQ = 85;
  public static final int UPDATE = 3;
  public static final int RTRIM = 43;
  public static final int UPPER = 47;
  public static final int _OREQ = 89;
  public static final int DROP = 13;
  public static final int WITH = 12;
  public static final int HAVING = 9;
  public static final int DISTINCT = 31;
  public static final int ILLEGAL_CHAR = 95;
  public static final int _COMMA = 92;
  public static final int TO_CHAR = 56;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECT",
  "UPDATE",
  "SET",
  "DELETE",
  "FROM",
  "WHERE",
  "GROUP",
  "HAVING",
  "IS",
  "NOT",
  "WITH",
  "DROP",
  "TABLE",
  "BY",
  "MERGE",
  "INTO",
  "NATURAL",
  "LEFT",
  "RIGHT",
  "FULL",
  "OUTER",
  "INNER",
  "JOIN",
  "USING",
  "SYSDATE",
  "TO_TIMESTAMP",
  "AS",
  "ON",
  "IN",
  "DISTINCT",
  "NULL",
  "COUNT",
  "SUM",
  "MAX",
  "MIN",
  "AVG",
  "LPAD",
  "RPAD",
  "LENGTH",
  "CONCAT",
  "LTRIM",
  "RTRIM",
  "INSTR",
  "REPLACE",
  "TRIM",
  "UPPER",
  "LOWER",
  "CHOOSE",
  "IIF",
  "NVL",
  "NVL2",
  "NULLIF",
  "ISNULL",
  "TO_DATE",
  "TO_CHAR",
  "CASE",
  "WHEN",
  "THEN",
  "ELSE",
  "END",
  "MATCHED",
  "IDENTIFIER",
  "INTEGER",
  "REAL",
  "LITERAL_STRING",
  "QTABLENAME",
  "TABDOTCOL",
  "QCOLALIAS",
  "_EQU",
  "_GT",
  "_LT",
  "_LET",
  "_GET",
  "_DIFF",
  "_DIFF2",
  "_PLUS",
  "_MINUS",
  "_DIVIDE",
  "_AND",
  "_OR",
  "_PLUSEQ",
  "_MINUSEQ",
  "_TIMESEQ",
  "_DIVIDEEQ",
  "_MODEQ",
  "_ANDEQ",
  "_POWEQ",
  "_OREQ",
  "_OPENPAR",
  "_CLOSEPAR",
  "_COMMA",
  "_STAR",
  "_SEMCOL2",
  "ILLEGAL_CHAR"
  };
}

