
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package com.kerberus.model.syntaxValidator.rules.sql;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
<<<<<<< HEAD
  public static final int AS = 19;
  public static final int LEFT = 12;
  public static final int IDENTIFIER = 47;
  public static final int REAL = 49;
  public static final int FROM = 6;
  public static final int LTRIM = 33;
  public static final int _GT = 55;
  public static final int OUTER = 15;
  public static final int NATURAL = 11;
  public static final int _DIFF2 = 60;
  public static final int RIGHT = 13;
  public static final int SUM = 25;
  public static final int _PLUSEQ = 66;
  public static final int JOIN = 17;
  public static final int INNER = 16;
  public static final int TO_DATE = 40;
  public static final int _LT = 56;
  public static final int INTEGER = 48;
  public static final int _CLOSEPAR = 75;
  public static final int NOT = 9;
  public static final int _OPENPAR = 74;
  public static final int MIN = 27;
  public static final int THEN = 44;
  public static final int _MINUSEQ = 67;
  public static final int LITERAL_STRING = 50;
  public static final int WHEN = 43;
  public static final int SELECT = 2;
  public static final int _AND = 64;
  public static final int FULL = 14;
  public static final int _POWEQ = 72;
  public static final int _DIVIDE = 63;
  public static final int _SEMCOL2 = 78;
  public static final int _LET = 57;
  public static final int IIF = 37;
  public static final int NULLIF = 39;
  public static final int DELETE = 5;
  public static final int TABDOTCOL = 52;
  public static final int QCOLALIAS = 53;
  public static final int _MINUS = 62;
  public static final int MAX = 26;
  public static final int _PLUS = 61;
  public static final int LPAD = 29;
  public static final int CONCAT = 32;
  public static final int ELSE = 45;
  public static final int _MODEQ = 70;
  public static final int INSTR = 35;
  public static final int LENGTH = 31;
  public static final int _GET = 58;
  public static final int AVG = 28;
  public static final int NULL = 23;
  public static final int EOF = 0;
  public static final int _STAR = 77;
  public static final int WHERE = 7;
  public static final int COUNT = 24;
  public static final int CHOOSE = 36;
  public static final int IS = 8;
  public static final int _EQU = 54;
  public static final int RPAD = 30;
  public static final int NVL2 = 38;
  public static final int IN = 21;
  public static final int SET = 4;
  public static final int error = 1;
  public static final int _OR = 65;
  public static final int ON = 20;
  public static final int END = 46;
  public static final int QTABLENAME = 51;
  public static final int USING = 18;
  public static final int _ANDEQ = 71;
  public static final int _DIFF = 59;
  public static final int _TIMESEQ = 68;
  public static final int CASE = 42;
  public static final int _DIVIDEEQ = 69;
  public static final int UPDATE = 3;
  public static final int RTRIM = 34;
  public static final int _OREQ = 73;
  public static final int WITH = 10;
  public static final int DISTINCT = 22;
  public static final int ILLEGAL_CHAR = 79;
  public static final int _COMMA = 76;
  public static final int TO_CHAR = 41;
=======
  public static final int AS = 17;
  public static final int LEFT = 10;
  public static final int IDENTIFIER = 40;
  public static final int REAL = 42;
  public static final int FROM = 6;
  public static final int _GT = 48;
  public static final int OUTER = 13;
  public static final int NATURAL = 9;
  public static final int _DIFF2 = 53;
  public static final int RIGHT = 11;
  public static final int SYSDATE = 16;
  public static final int _PLUSEQ = 59;
  public static final int NVL = 24;
  public static final int JOIN = 15;
  public static final int INNER = 14;
  public static final int _LT = 49;
  public static final int INTEGER = 41;
  public static final int _CLOSEPAR = 68;
  public static final int _OPENPAR = 67;
  public static final int THEN = 37;
  public static final int _MINUSEQ = 60;
  public static final int LITERAL_STRING = 43;
  public static final int TRIM = 30;
  public static final int LOWER = 32;
  public static final int WHEN = 36;
  public static final int SELECT = 2;
  public static final int _AND = 57;
  public static final int FULL = 12;
  public static final int _DIVIDE = 56;
  public static final int _POWEQ = 65;
  public static final int _SEMCOL2 = 71;
  public static final int _LET = 50;
  public static final int IIF = 34;
  public static final int DELETE = 5;
  public static final int TABDOTCOL = 45;
  public static final int QCOLALIAS = 46;
  public static final int _MINUS = 55;
  public static final int _PLUS = 54;
  public static final int LPAD = 26;
  public static final int CONCAT = 25;
  public static final int ELSE = 38;
  public static final int _MODEQ = 63;
  public static final int LENGTH = 28;
  public static final int _GET = 51;
  public static final int AVG = 23;
  public static final int NULL = 21;
  public static final int EOF = 0;
  public static final int WHERE = 7;
  public static final int _STAR = 70;
  public static final int COUNT = 22;
  public static final int CHOOSE = 33;
  public static final int _EQU = 47;
  public static final int RPAD = 27;
  public static final int IN = 19;
  public static final int SET = 4;
  public static final int error = 1;
  public static final int _OR = 58;
  public static final int ON = 18;
  public static final int END = 39;
  public static final int REPLACE = 29;
  public static final int QTABLENAME = 44;
  public static final int _ANDEQ = 64;
  public static final int _DIFF = 52;
  public static final int _TIMESEQ = 61;
  public static final int CASE = 35;
  public static final int _DIVIDEEQ = 62;
  public static final int UPDATE = 3;
  public static final int UPPER = 31;
  public static final int _OREQ = 66;
  public static final int WITH = 8;
  public static final int DISTINCT = 20;
  public static final int ILLEGAL_CHAR = 72;
  public static final int _COMMA = 69;
>>>>>>> release-0.3-merging_branch
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECT",
  "UPDATE",
  "SET",
  "DELETE",
  "FROM",
  "WHERE",
  "IS",
  "NOT",
  "WITH",
  "NATURAL",
  "LEFT",
  "RIGHT",
  "FULL",
  "OUTER",
  "INNER",
  "JOIN",
<<<<<<< HEAD
  "USING",
=======
  "SYSDATE",
>>>>>>> release-0.3-merging_branch
  "AS",
  "ON",
  "IN",
  "DISTINCT",
  "NULL",
  "COUNT",
  "SUM",
  "MAX",
  "MIN",
  "AVG",
  "NVL",
  "CONCAT",
  "LPAD",
  "RPAD",
  "LENGTH",
<<<<<<< HEAD
  "CONCAT",
  "LTRIM",
  "RTRIM",
  "INSTR",
=======
  "REPLACE",
  "TRIM",
  "UPPER",
  "LOWER",
>>>>>>> release-0.3-merging_branch
  "CHOOSE",
  "IIF",
  "NVL2",
  "NULLIF",
  "TO_DATE",
  "TO_CHAR",
  "CASE",
  "WHEN",
  "THEN",
  "ELSE",
  "END",
  "IDENTIFIER",
  "INTEGER",
  "REAL",
  "LITERAL_STRING",
  "QTABLENAME",
  "TABDOTCOL",
  "QCOLALIAS",
  "_EQU",
  "_GT",
  "_LT",
  "_LET",
  "_GET",
  "_DIFF",
  "_DIFF2",
  "_PLUS",
  "_MINUS",
  "_DIVIDE",
  "_AND",
  "_OR",
  "_PLUSEQ",
  "_MINUSEQ",
  "_TIMESEQ",
  "_DIVIDEEQ",
  "_MODEQ",
  "_ANDEQ",
  "_POWEQ",
  "_OREQ",
  "_OPENPAR",
  "_CLOSEPAR",
  "_COMMA",
  "_STAR",
  "_SEMCOL2",
  "ILLEGAL_CHAR"
  };
}

